//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarathonSkillsApp.DB_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KitContents
    {
        public int KitTypeID { get; set; }
        public int InventoryID { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        public virtual KitTypes KitTypes { get; set; }
    }
}
